// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these values with your actual Firebase project configuration
  // Run: flutterfire configure
  // Or get values from Firebase Console > Project Settings > General

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZKgwBXojeGvfo3bOOMKK1cR0iSuMpjsw',
    appId: '1:96030530148:web:cb1cd9ec94a5992829dd71',
    messagingSenderId: '96030530148',
    projectId: 'toastlabplus',
    authDomain: 'toastlabplus.firebaseapp.com',
    storageBucket: 'toastlabplus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqm9Ygd44xd2b2tlpFIKCiIAMe-v6HtQc',
    appId: '1:96030530148:android:80f2861cf77a169629dd71',
    messagingSenderId: '96030530148',
    projectId: 'toastlabplus',
    storageBucket: 'toastlabplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAv9tmgvqstnrUzQ6_CgjSRftW8x5OTUg',
    appId: '1:96030530148:ios:f20d2b4454e8e64f29dd71',
    messagingSenderId: '96030530148',
    projectId: 'toastlabplus',
    storageBucket: 'toastlabplus.firebasestorage.app',
    iosClientId: '96030530148-etk7qjsgk6lsv0ds2mh2dm6k1p4ck4no.apps.googleusercontent.com',
    iosBundleId: 'com.skipandsnow.toastlabplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAv9tmgvqstnrUzQ6_CgjSRftW8x5OTUg',
    appId: '1:96030530148:ios:f20d2b4454e8e64f29dd71',
    messagingSenderId: '96030530148',
    projectId: 'toastlabplus',
    storageBucket: 'toastlabplus.firebasestorage.app',
    iosClientId: '96030530148-etk7qjsgk6lsv0ds2mh2dm6k1p4ck4no.apps.googleusercontent.com',
    iosBundleId: 'com.skipandsnow.toastlabplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZKgwBXojeGvfo3bOOMKK1cR0iSuMpjsw',
    appId: '1:96030530148:web:4d124f442203396929dd71',
    messagingSenderId: '96030530148',
    projectId: 'toastlabplus',
    authDomain: 'toastlabplus.firebaseapp.com',
    storageBucket: 'toastlabplus.firebasestorage.app',
  );

}