# Standard Flutter Podfile setup
require_relative 'Flutter/generated_xcode_build_settings.rb'
use_frameworks!

# Flutter Pod Helper
load File.join(FLUTTER_ROOT, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

# Define global platform
platform :ios, '18.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Ensure all pods use iOS 18.0 minimum to match the project
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
    end
  end
end
